name: Release

on:
    push:
        tags:
            - "*"

env:
    typst_paper: Typst-Paper-Template

jobs:
    build:
        name: release
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Zip
              id: zip
              run: |
                  mkdir ${{ env.typst_paper }}
                  cp main.typ paper_template.typ ${{ env.typst_paper }}
                  zip -r ${{ env.typst_paper }}.zip ./${{ env.typst_paper }}
                  ls
                  echo "tag_name=$(git tag --sort version:refname | tail -n 1)" >> $GITHUB_OUTPUT

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
                  VERSION: ${{ github.ref }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: ${{ github.ref }}
                  draft: false
                  prerelease: false

            - name: Upload zip file
              id: upload-zip
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./${{ env.typst_paper }}.zip
                  asset_name: ${{ env.typst_paper }}-${{ github.ref_name }}.zip
                  asset_content_type: application/zip

            - name: Upload
              id: upload-main
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./template/main.typ
                  asset_name: main.typ
                  asset_content_type: text/typst

            - name: Upload
              id: upload-example
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./example.typ
                  asset_name: example.typ
                  asset_content_type: text/typst

            - name: Upload paper template
              id: upload-template
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./paper_template.typ
                  asset_name: paper_template.typ
                  asset_content_type: text/typst
